{"name": "Verify login functionality", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0089B8F3+2406643]\n\tOrdinal0 [0x0082AF31+1945393]\n\tOrdinal0 [0x0071C748+837448]\n\tOrdinal0 [0x00739994+956820]\n\tOrdinal0 [0x00735D71+941425]\n\tOrdinal0 [0x00768EE0+1150688]\n\tOrdinal0 [0x00768B3A+1149754]\n\tOrdinal0 [0x00764096+1130646]\n\tOrdinal0 [0x0073E636+976438]\n\tOrdinal0 [0x0073F546+980294]\n\tGetHandleVerifier [0x00B09612+2498066]\n\tGetHandleVerifier [0x00AFC920+2445600]\n\tGetHandleVerifier [0x00934F2A+579370]\n\tGetHandleVerifier [0x00933D36+574774]\n\tOrdinal0 [0x00831C0B+1973259]\n\tOrdinal0 [0x00836688+1992328]\n\tOrdinal0 [0x00836775+1992565]\n\tOrdinal0 [0x0083F8D1+2029777]\n\tBaseThreadInitThunk [0x76CBFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77627A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77627A4E+238]\n\n", "trace": "  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\LoginPageSteps.py\", line 23, in step_impl\n    context.driver = webdriver.Chrome(ChromeDriverManager().install())\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 93, in __init__\n    RemoteWebDriver.__init__(\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch the App", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.\n  (chrome not reachable)\n  (The process started from chrome location C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0089B8F3+2406643]\n\tOrdinal0 [0x0082AF31+1945393]\n\tOrdinal0 [0x0071C748+837448]\n\tOrdinal0 [0x00739994+956820]\n\tOrdinal0 [0x00735D71+941425]\n\tOrdinal0 [0x00768EE0+1150688]\n\tOrdinal0 [0x00768B3A+1149754]\n\tOrdinal0 [0x00764096+1130646]\n\tOrdinal0 [0x0073E636+976438]\n\tOrdinal0 [0x0073F546+980294]\n\tGetHandleVerifier [0x00B09612+2498066]\n\tGetHandleVerifier [0x00AFC920+2445600]\n\tGetHandleVerifier [0x00934F2A+579370]\n\tGetHandleVerifier [0x00933D36+574774]\n\tOrdinal0 [0x00831C0B+1973259]\n\tOrdinal0 [0x00836688+1992328]\n\tOrdinal0 [0x00836775+1992565]\n\tOrdinal0 [0x0083F8D1+2029777]\n\tBaseThreadInitThunk [0x76CBFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77627A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77627A4E+238]\n\n", "trace": "  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\LoginPageSteps.py\", line 23, in step_impl\n    context.driver = webdriver.Chrome(ChromeDriverManager().install())\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 93, in __init__\n    RemoteWebDriver.__init__(\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"F:\\baitap\\kiemthu\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1651739664683, "stop": 1651739672978}, {"name": "When enter key to input login credentials and click button", "status": "skipped", "start": 1651739672979, "stop": 1651739672979}], "start": 1651739664681, "stop": 1651739672979, "uuid": "2b1333f0-4418-4776-a06e-c560fa924744", "historyId": "ab7dfe44a20221545b84346a3128c6f4", "fullName": "Test the c2ta application: Verify login functionality", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test the c2ta application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}